language: node_js

node_js: 
  - 'lts/*'

script:
  #- ./download.sh
  - time ./run.sh
  - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir ./reposense-report

before_install:
  - npm install -g netlify-cli

cache: npm
