language: node_js

node_js: 
  - 'lts/*'

script:
  - ./download.sh && time ./run.sh && pwd && ls && netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p ./reposense-report

before_install:
  - npm install -g netlify-cli

cache: npm
